// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUAFkUD8d-CKQejJo67xmjCI5yK3pDho8',
    appId: '1:923319571278:web:287e236b5d8bff6c68c41f',
    messagingSenderId: '923319571278',
    projectId: 'color-grid-app',
    authDomain: 'color-grid-app.firebaseapp.com',
    storageBucket: 'color-grid-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-CUpN7t8zS6SWWxaVHb4e4xDq368QAwo',
    appId: '1:923319571278:android:96b1cdc4c1971d6468c41f',
    messagingSenderId: '923319571278',
    projectId: 'color-grid-app',
    storageBucket: 'color-grid-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4ZCcbCSJWWOW_EFY3bvSVTFb7T4GdZRE',
    appId: '1:923319571278:ios:ed880cd44566832a68c41f',
    messagingSenderId: '923319571278',
    projectId: 'color-grid-app',
    storageBucket: 'color-grid-app.appspot.com',
    iosClientId: '923319571278-g25ko409efh7a2mod0gcqnqn79bitjli.apps.googleusercontent.com',
    iosBundleId: 'com.eveylan.colorGrid',
  );
}
